apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: hipster-demo
  annotations:
    external-dns.alpha.kubernetes.io/hostname: hipster.gvcl.lab-01.clg.nos.pt.
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - name: http
    port: 80
    targetPort: 8080
