apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: hipster
  namespace: hipster-demo
spec:
  domains:
    - hipster.${fqdn}
---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: frontendconfig
  namespace: hipster-demo
spec:
  redirectToHttps:
    enabled: true
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hipster-ingress
  namespace: hipster-demo
  annotations:
    kubernetes.io/ingress.allow-http: "true"
    networking.gke.io/managed-certificates: hipster
    networking.gke.io/v1beta1.FrontendConfig: "frontendconfig"
spec:
  rules:
    - host: hipster.${fqdn}
      http:
        paths:
        - backend:
            serviceName: frontend
            servicePort: 80
